### ISSUE TITLE
Wrong insets

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/fmx_tutorials#6]
```
unit Unit1;

interface

uses
  System.SysUtils, System.Classes, System.UITypes,

  FMX.Controls, FMX.Controls.Presentation, FMX.StdCtrls, FMX.Types, FMX.Forms,
  FMX.Graphics,

  iPub.FMX.SystemBars;

type
  TForm1 = class(TForm)
    Label1: TLabel;
    procedure OnInsetsChange(Sender: TObject);
    procedure FormCreate(Sender: TObject);
  end;

var
  Form1: TForm1;

implementation

{$R *.fmx}

procedure TForm1.OnInsetsChange(Sender: TObject);
begin
  Label1.Text := 'L:' + Form1.SystemBars.Insets.Left.ToString +
              ' / T:' + Form1.SystemBars.Insets.Top.ToString +
              ' / R:' + Form1.SystemBars.Insets.Right.ToString +
              ' / B:' + Form1.SystemBars.Insets.Bottom.ToString;
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  Form1.Fill.Color := TAlphaColorRec.Darkgray;
  Form1.Fill.Kind := TBrushKind.Solid;

  Form1.SystemBars.StatusBarBackgroundColor := TAlphaColorRec.Null;
  Form1.SystemBars.NavigationBarBackgroundColor := TAlphaColorRec.Null;
  Form1.SystemBars.Visibility := TipFormSystemBars.TVisibilityMode.VisibleAndOverlap;
  Form1.SystemBars.OnInsetsChange := OnInsetsChange;
end;

end.
```

0. Create a unit like the unit above
1. Set "Double cutout" in System > Options > Developer options > Display cutout
2. Change in [iPub.FMX.SystemBars.Android:1064] the line `if AMode = TipFormSystemBars.TVisibilityMode.Invisible then` to `if AMode = TipFormSystemBars.TVisibilityMode.VisibleAndOverlap then`
3. Now check the insets: every inset is null except the "Top" 😶

![IMG_2595](https://user-images.githubusercontent.com/3335273/129886843-a6166ecb-f953-4ac8-b125-0e846f7dfa10.JPG)
![IMG_2596](https://user-images.githubusercontent.com/3335273/129886848-57d8c1d0-2667-4ca6-a1e3-b059d51f162a.JPG)

**Comment by kazuser** [comment]
BTW: Android 11

**Comment by viniciusfbb** [comment]
You are trying to make a customization in the TipSystemBars code that is not as simple as it sounds. TipSystemBars is designed to work in Visible and VisibleAndOverlap mode with LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT, which is the layout used by 99% of non-game apps (Chrome, standard android apps, etc). And in the case of games, 99% use fullscreen, and for that I created the Invisible mode.

There is no reason to create other modes, because it is beyond the purpose of TipSystemBars, which was created to simplify the settings, because on android there are thousands of combinations of existing settings for each android version and for each peculiarity of the display and manufacturer. It's already a very big feat to have summarized everything in just 3 properties, no wonder there are 2 thousand lines just for that.

TipSystemBars has been tested on several devices with all androids compatible with the latest Delphi, and Insets as well as TappableInsets are working normally (in non-custom code).

**Comment by kazuser** [comment]
Ok, but even without any modifications the insets are null (and the "window" is smaller and it looks ugly) 😕

![IMG_2597](https://user-images.githubusercontent.com/3335273/129901003-3b8e9641-c8d0-44ee-9815-f4f41870b390.JPG)
![IMG_2598](https://user-images.githubusercontent.com/3335273/129900978-44655f3e-c3be-48cb-b0e8-9b210c109ec3.JPG)

**Comment by viniciusfbb** [comment]
> Ok, but even without any modifications the insets are null (and the "window" is smaller and it looks ugly) 😕

That's how it works.

![delphi](https://user-images.githubusercontent.com/11139086/129906098-57c6fc4b-aecd-4e85-8cc6-0c5fc7948352.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/11139086/129906129-92b47f50-a8a5-4230-8ddc-27249fce0c20.png)
